apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agrotrust

resources:
  - namespace.yaml
  - configmap.yaml
  - secret-template.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/part-of: agrotrust-ai
  app.kubernetes.io/managed-by: kustomize
